Lab 1
Sparty27/Nyshchyi-Nazar-IPZ-32 pull request #1
Opened 2023-09-09 08:58 UTC by Sparty27

2023-09-09 09:41 UTC, Sparty27 commented
https://sparty27.github.io/Nyshchyi-Nazar-IPZ-32/

2023-09-09 09:47 UTC, vozniuk-lntu requested changes

2023-09-09 09:47 UTC, vozniuk-lntu commented on index.html
> +        <a href="#">Студія</a>
це в нас список

2023-09-09 09:47 UTC, vozniuk-lntu commented on index.html
> +      <a href="">info@devstudio.com</a>
це список, активні списки

2023-09-09 09:47 UTC, vozniuk-lntu commented on index.html
> +      <section>
можна додати прихований заголовок

2023-09-09 09:47 UTC, vozniuk-lntu commented on index.html
> +      <address>
тут список і активні ссилки tel i mailto

2023-09-11 14:05 UTC, vozniuk-lntu commented on index.html
> +        <a href="#">Студія</a>
plus

2023-09-11 14:11 UTC, vozniuk-lntu requested changes

2023-09-11 14:11 UTC, vozniuk-lntu commented on index.html
> +        <h2 hidden>Ефективні рішення для вашого бізнесу</h2>
та не сюди, а в наступну секцію, тут він не треба є h1

2023-09-11 14:11 UTC, vozniuk-lntu commented on index.html
> +        <h2 hidden>Наша команда</h2>
не потрібно додавати прихований заголовок якщо є звичайний

2023-09-11 14:11 UTC, vozniuk-lntu commented on index.html
> +        <ul>
має десь бути тег адрес
як варіант обгортати список твій

2023-09-11 14:16 UTC, vozniuk-lntu requested changes

2023-09-11 14:16 UTC, vozniuk-lntu commented on index.html
> +            <img src="Images/image1.jpg" alt="programming" width="370" />
такий собі alt

2023-09-11 14:17 UTC, vozniuk-lntu commented on index.html
> +              href="https://www.google.com/maps?q=50.4267485,30.5381659"
посилання на сторонній сайт
треба додати атрибут rel

2023-09-11 14:18 UTC, vozniuk-lntu requested changes

2023-09-11 14:18 UTC, vozniuk-lntu commented on index.html
> +              href="https://www.google.com/maps?q=50.4267485,30.5381659"
посилання на сторонній сайт
треба додати атрибут rel

2023-09-11 15:10 UTC, xm1ls commented
Ку

2023-09-11 15:12 UTC, Sparty27 commented
> Ку

Привіт

2023-09-11 19:22 UTC, vozniuk-lntu approved these changes
я апрувлю, назву папки зміниш у наступній гілці
зливай в мейн
перевір чи деплоїться
нову гілку з мейн робиш
наступна лаба
https://docs.google.com/document/d/1THT3lT1JlDAHJNTSdngiToexdVmUeLbE/edit?usp=sharing&ouid=104518963218417128491&rtpof=true&sd=true
і скрін як буде виглядати (працюєш суто з шрифтами та кольорами)
https://i.imgur.com/tniDQxh.png

2023-09-11 19:22 UTC, vozniuk-lntu commented on index.html
> +            <img src="Images/image2.jpg" alt="Телефон і макет компонентів до нього" width="370" />
помітила що Images з великої
так не називають, тільки нижній регістр

2023-09-12 16:07 UTC, merged